<?xml version="1.0" encoding="utf-8"?>
<Database Name="Content" EntityNamespace="MusicContext" ContextNamespace="Musics" Class="MusicDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=mssql2.1gb.ua;Initial Catalog=1gb_Tina;User ID=1gb_amc" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ContentConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Albums" Member="Albums">
    <Type Name="Album">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="Year" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Image" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Association Name="Album_Song" Member="Songs" ThisKey="ID" OtherKey="AlbumId" Type="Song" />
    </Type>
  </Table>
  <Table Name="dbo.Songs" Member="Songs">
    <Type Name="Song">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="Source" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Length" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AlbumId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Album_Song" Member="Album" ThisKey="AlbumId" OtherKey="ID" Type="Album" IsForeignKey="true" />
    </Type>
  </Table>
</Database>