<?xml version="1.0" encoding="utf-8"?>
<Database Name="tinakar_content" Class="TourDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=mssql2.hosting.ua;Initial Catalog=tinakar_content;Persist Security Info=True;User ID=tinakar_content" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="_1gb_TinaConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Tours" Member="Tours">
    <Type Name="Tour">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="Year" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LeftText" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="RightTitle" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="RightSubTitle" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="RightText" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="BackgroundImage" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="BlackText" Type="System.Boolean" DbType="bit" CanBeNull="false" />
      <Column Name="LeftTextColor" Type="System.String" DbType="varchar(7)" CanBeNull="true" />
      <Association Name="Tour_TourPicture" Member="TourPictures" ThisKey="ID" OtherKey="TourID" Type="TourPicture" />
    </Type>
  </Table>
  <Table Name="dbo.TourPictures" Member="TourPictures">
    <Type Name="TourPicture">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Picture" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Preview" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="TourID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SortOrder" Type="System.Int32" DbType="int" CanBeNull="false" />
      <Association Name="Tour_TourPicture" Member="Tour" ThisKey="TourID" OtherKey="ID" Type="Tour" IsForeignKey="true" />
    </Type>
  </Table>
</Database>