//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4200
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("gbua_tripsModel", "BrandsCarAds", "Brands", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Trips.Mvc.Models.Brand), "CarAds", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Trips.Mvc.Models.CarAd))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("gbua_tripsModel", "CarAdsCarAdDescriptions", "CarAds", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Trips.Mvc.Models.CarAd), "CarAdDescriptions", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Trips.Mvc.Models.CarAdDescription))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("gbua_tripsModel", "CarAdCarAdImage", "CarAd", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Trips.Mvc.Models.CarAd), "CarAdImage", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Trips.Mvc.Models.CarAdImage))]

// Original file name:
// Generation date: 27.02.2010 13:22:35
namespace Trips.Mvc.Models
{
    
    /// <summary>
    /// There are no comments for CarAdStorage in the schema.
    /// </summary>
    public partial class CarAdStorage : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new CarAdStorage object using the connection string found in the 'CarAdStorage' section of the application configuration file.
        /// </summary>
        public CarAdStorage() : 
                base("name=CarAdStorage", "CarAdStorage")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new CarAdStorage object.
        /// </summary>
        public CarAdStorage(string connectionString) : 
                base(connectionString, "CarAdStorage")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new CarAdStorage object.
        /// </summary>
        public CarAdStorage(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "CarAdStorage")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for Brands in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Brand> Brands
        {
            get
            {
                if ((this._Brands == null))
                {
                    this._Brands = base.CreateQuery<Brand>("[Brands]");
                }
                return this._Brands;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Brand> _Brands;
        /// <summary>
        /// There are no comments for CarAdDescriptions in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<CarAdDescription> CarAdDescriptions
        {
            get
            {
                if ((this._CarAdDescriptions == null))
                {
                    this._CarAdDescriptions = base.CreateQuery<CarAdDescription>("[CarAdDescriptions]");
                }
                return this._CarAdDescriptions;
            }
        }
        private global::System.Data.Objects.ObjectQuery<CarAdDescription> _CarAdDescriptions;
        /// <summary>
        /// There are no comments for CarAdImages in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<CarAdImage> CarAdImages
        {
            get
            {
                if ((this._CarAdImages == null))
                {
                    this._CarAdImages = base.CreateQuery<CarAdImage>("[CarAdImages]");
                }
                return this._CarAdImages;
            }
        }
        private global::System.Data.Objects.ObjectQuery<CarAdImage> _CarAdImages;
        /// <summary>
        /// There are no comments for CarAds in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<CarAd> CarAds
        {
            get
            {
                if ((this._CarAds == null))
                {
                    this._CarAds = base.CreateQuery<CarAd>("[CarAds]");
                }
                return this._CarAds;
            }
        }
        private global::System.Data.Objects.ObjectQuery<CarAd> _CarAds;
        /// <summary>
        /// There are no comments for Brands in the schema.
        /// </summary>
        public void AddToBrands(Brand brand)
        {
            base.AddObject("Brands", brand);
        }
        /// <summary>
        /// There are no comments for CarAdDescriptions in the schema.
        /// </summary>
        public void AddToCarAdDescriptions(CarAdDescription carAdDescription)
        {
            base.AddObject("CarAdDescriptions", carAdDescription);
        }
        /// <summary>
        /// There are no comments for CarAdImages in the schema.
        /// </summary>
        public void AddToCarAdImages(CarAdImage carAdImage)
        {
            base.AddObject("CarAdImages", carAdImage);
        }
        /// <summary>
        /// There are no comments for CarAds in the schema.
        /// </summary>
        public void AddToCarAds(CarAd carAd)
        {
            base.AddObject("CarAds", carAd);
        }
    }
    /// <summary>
    /// There are no comments for gbua_tripsModel.Brand in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="gbua_tripsModel", Name="Brand")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Brand : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Brand object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="published">Initial value of Published.</param>
        public static Brand CreateBrand(long id, string name, bool published)
        {
            Brand brand = new Brand();
            brand.Id = id;
            brand.Name = name;
            brand.Published = published;
            return brand;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private long _Id;
        partial void OnIdChanging(long value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Published in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public bool Published
        {
            get
            {
                return this._Published;
            }
            set
            {
                this.OnPublishedChanging(value);
                this.ReportPropertyChanging("Published");
                this._Published = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Published");
                this.OnPublishedChanged();
            }
        }
        private bool _Published;
        partial void OnPublishedChanging(bool value);
        partial void OnPublishedChanged();
        /// <summary>
        /// There are no comments for CarAds in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("gbua_tripsModel", "BrandsCarAds", "CarAds")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<CarAd> CarAds
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<CarAd>("gbua_tripsModel.BrandsCarAds", "CarAds");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<CarAd>("gbua_tripsModel.BrandsCarAds", "CarAds", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for gbua_tripsModel.CarAdDescription in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="gbua_tripsModel", Name="CarAdDescription")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class CarAdDescription : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new CarAdDescription object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        /// <param name="language">Initial value of Language.</param>
        public static CarAdDescription CreateCarAdDescription(long id, string language)
        {
            CarAdDescription carAdDescription = new CarAdDescription();
            carAdDescription.Id = id;
            carAdDescription.Language = language;
            return carAdDescription;
        }
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this.ReportPropertyChanging("Description");
                this._Description = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Description");
                this.OnDescriptionChanged();
            }
        }
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private long _Id;
        partial void OnIdChanging(long value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Keywords in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Keywords
        {
            get
            {
                return this._Keywords;
            }
            set
            {
                this.OnKeywordsChanging(value);
                this.ReportPropertyChanging("Keywords");
                this._Keywords = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Keywords");
                this.OnKeywordsChanged();
            }
        }
        private string _Keywords;
        partial void OnKeywordsChanging(string value);
        partial void OnKeywordsChanged();
        /// <summary>
        /// There are no comments for Property Language in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Language
        {
            get
            {
                return this._Language;
            }
            set
            {
                this.OnLanguageChanging(value);
                this.ReportPropertyChanging("Language");
                this._Language = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Language");
                this.OnLanguageChanged();
            }
        }
        private string _Language;
        partial void OnLanguageChanging(string value);
        partial void OnLanguageChanged();
        /// <summary>
        /// There are no comments for Property ShortDescription in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ShortDescription
        {
            get
            {
                return this._ShortDescription;
            }
            set
            {
                this.OnShortDescriptionChanging(value);
                this.ReportPropertyChanging("ShortDescription");
                this._ShortDescription = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("ShortDescription");
                this.OnShortDescriptionChanged();
            }
        }
        private string _ShortDescription;
        partial void OnShortDescriptionChanging(string value);
        partial void OnShortDescriptionChanged();
        /// <summary>
        /// There are no comments for Property Text in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Text
        {
            get
            {
                return this._Text;
            }
            set
            {
                this.OnTextChanging(value);
                this.ReportPropertyChanging("Text");
                this._Text = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Text");
                this.OnTextChanged();
            }
        }
        private string _Text;
        partial void OnTextChanging(string value);
        partial void OnTextChanged();
        /// <summary>
        /// There are no comments for CarAds in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("gbua_tripsModel", "CarAdsCarAdDescriptions", "CarAds")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public CarAd CarAds
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<CarAd>("gbua_tripsModel.CarAdsCarAdDescriptions", "CarAds").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<CarAd>("gbua_tripsModel.CarAdsCarAdDescriptions", "CarAds").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for CarAds in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<CarAd> CarAdsReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<CarAd>("gbua_tripsModel.CarAdsCarAdDescriptions", "CarAds");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<CarAd>("gbua_tripsModel.CarAdsCarAdDescriptions", "CarAds", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for gbua_tripsModel.CarAdImage in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="gbua_tripsModel", Name="CarAdImage")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class CarAdImage : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new CarAdImage object.
        /// </summary>
        /// <param name="default">Initial value of Default.</param>
        /// <param name="id">Initial value of Id.</param>
        /// <param name="imageSource">Initial value of ImageSource.</param>
        public static CarAdImage CreateCarAdImage(bool @default, long id, string imageSource)
        {
            CarAdImage carAdImage = new CarAdImage();
            carAdImage.Default = @default;
            carAdImage.Id = id;
            carAdImage.ImageSource = imageSource;
            return carAdImage;
        }
        /// <summary>
        /// There are no comments for Property Default in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public bool Default
        {
            get
            {
                return this._Default;
            }
            set
            {
                this.OnDefaultChanging(value);
                this.ReportPropertyChanging("Default");
                this._Default = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Default");
                this.OnDefaultChanged();
            }
        }
        private bool _Default;
        partial void OnDefaultChanging(bool value);
        partial void OnDefaultChanged();
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private long _Id;
        partial void OnIdChanging(long value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property ImageSource in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageSource
        {
            get
            {
                return this._ImageSource;
            }
            set
            {
                this.OnImageSourceChanging(value);
                this.ReportPropertyChanging("ImageSource");
                this._ImageSource = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("ImageSource");
                this.OnImageSourceChanged();
            }
        }
        private string _ImageSource;
        partial void OnImageSourceChanging(string value);
        partial void OnImageSourceChanged();
        /// <summary>
        /// There are no comments for CarAd in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("gbua_tripsModel", "CarAdCarAdImage", "CarAd")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public CarAd CarAd
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<CarAd>("gbua_tripsModel.CarAdCarAdImage", "CarAd").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<CarAd>("gbua_tripsModel.CarAdCarAdImage", "CarAd").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for CarAd in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<CarAd> CarAdReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<CarAd>("gbua_tripsModel.CarAdCarAdImage", "CarAd");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<CarAd>("gbua_tripsModel.CarAdCarAdImage", "CarAd", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for gbua_tripsModel.CarAd in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="gbua_tripsModel", Name="CarAd")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class CarAd : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new CarAd object.
        /// </summary>
        /// <param name="class">Initial value of Class.</param>
        /// <param name="id">Initial value of Id.</param>
        /// <param name="model">Initial value of Model.</param>
        /// <param name="year">Initial value of Year.</param>
        public static CarAd CreateCarAd(long @class, long id, string model, long year)
        {
            CarAd carAd = new CarAd();
            carAd.Class = @class;
            carAd.Id = id;
            carAd.Model = model;
            carAd.Year = year;
            return carAd;
        }
        /// <summary>
        /// There are no comments for Property Class in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long Class
        {
            get
            {
                return this._Class;
            }
            set
            {
                this.OnClassChanging(value);
                this.ReportPropertyChanging("Class");
                this._Class = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Class");
                this.OnClassChanged();
            }
        }
        private long _Class;
        partial void OnClassChanging(long value);
        partial void OnClassChanged();
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private long _Id;
        partial void OnIdChanging(long value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Model in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Model
        {
            get
            {
                return this._Model;
            }
            set
            {
                this.OnModelChanging(value);
                this.ReportPropertyChanging("Model");
                this._Model = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Model");
                this.OnModelChanged();
            }
        }
        private string _Model;
        partial void OnModelChanging(string value);
        partial void OnModelChanged();
        /// <summary>
        /// There are no comments for Property Year in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long Year
        {
            get
            {
                return this._Year;
            }
            set
            {
                this.OnYearChanging(value);
                this.ReportPropertyChanging("Year");
                this._Year = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Year");
                this.OnYearChanged();
            }
        }
        private long _Year;
        partial void OnYearChanging(long value);
        partial void OnYearChanged();
        /// <summary>
        /// There are no comments for Brand in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("gbua_tripsModel", "BrandsCarAds", "Brands")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Brand Brand
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Brand>("gbua_tripsModel.BrandsCarAds", "Brands").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Brand>("gbua_tripsModel.BrandsCarAds", "Brands").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Brand in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Brand> BrandReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Brand>("gbua_tripsModel.BrandsCarAds", "Brands");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Brand>("gbua_tripsModel.BrandsCarAds", "Brands", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Descriptions in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("gbua_tripsModel", "CarAdsCarAdDescriptions", "CarAdDescriptions")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<CarAdDescription> Descriptions
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<CarAdDescription>("gbua_tripsModel.CarAdsCarAdDescriptions", "CarAdDescriptions");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<CarAdDescription>("gbua_tripsModel.CarAdsCarAdDescriptions", "CarAdDescriptions", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Images in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("gbua_tripsModel", "CarAdCarAdImage", "CarAdImage")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<CarAdImage> Images
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<CarAdImage>("gbua_tripsModel.CarAdCarAdImage", "CarAdImage");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<CarAdImage>("gbua_tripsModel.CarAdCarAdImage", "CarAdImage", value);
                }
            }
        }
    }
}
