<?xml version="1.0" encoding="utf-8"?>
<Database Name="drozd_Maestro" Class="VideosDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=mssql011007.hosting.ua;Initial Catalog=drozd_Maestro;User ID=drozd_maestro" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="_1gb_MaestroConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="Drozd_maestro.Videos" Member="Videos">
    <Type Name="Video">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TitleTextID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Embed" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
</Database>