//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4206
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("shop_Orders", "OrderOrderItem", "Order", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Shop.Models.Order), "OrderItem", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Shop.Models.OrderItem))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("shop_Orders", "DeliveryTypeOrder", "DeliveryType", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Shop.Models.DeliveryType), "Order", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Shop.Models.Order))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("shop_Orders", "DeliveryTypePaymentType", "DeliveryType", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Shop.Models.DeliveryType), "PaymentType", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Shop.Models.PaymentType))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("shop_Orders", "PaymentTypeOrder", "PaymentType", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Shop.Models.PaymentType), "Order", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Shop.Models.Order))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("shop_Orders", "PaymentTypePaymentProperty", "PaymentType", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Shop.Models.PaymentType), "PaymentProperty", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Shop.Models.PaymentProperty))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("shop_Orders", "PaymentPropertyPaymentPropertyValue", "PaymentProperty", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Shop.Models.PaymentProperty), "PaymentPropertyValue", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Shop.Models.PaymentPropertyValue))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("shop_Orders", "OrderPaymentPropertyValue", "Order", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Shop.Models.Order), "PaymentPropertyValue", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Shop.Models.PaymentPropertyValue))]

// Original file name:
// Generation date: 31.08.2010 23:19:24
namespace Shop.Models
{
    
    /// <summary>
    /// There are no comments for OrdersStorage in the schema.
    /// </summary>
    public partial class OrdersStorage : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new OrdersStorage object using the connection string found in the 'OrdersStorage' section of the application configuration file.
        /// </summary>
        public OrdersStorage() : 
                base("name=OrdersStorage", "OrdersStorage")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new OrdersStorage object.
        /// </summary>
        public OrdersStorage(string connectionString) : 
                base(connectionString, "OrdersStorage")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new OrdersStorage object.
        /// </summary>
        public OrdersStorage(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "OrdersStorage")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for Orders in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Order> Orders
        {
            get
            {
                if ((this._Orders == null))
                {
                    this._Orders = base.CreateQuery<Order>("[Orders]");
                }
                return this._Orders;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Order> _Orders;
        /// <summary>
        /// There are no comments for OrderItems in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<OrderItem> OrderItems
        {
            get
            {
                if ((this._OrderItems == null))
                {
                    this._OrderItems = base.CreateQuery<OrderItem>("[OrderItems]");
                }
                return this._OrderItems;
            }
        }
        private global::System.Data.Objects.ObjectQuery<OrderItem> _OrderItems;
        /// <summary>
        /// There are no comments for DeliveryTypes in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<DeliveryType> DeliveryTypes
        {
            get
            {
                if ((this._DeliveryTypes == null))
                {
                    this._DeliveryTypes = base.CreateQuery<DeliveryType>("[DeliveryTypes]");
                }
                return this._DeliveryTypes;
            }
        }
        private global::System.Data.Objects.ObjectQuery<DeliveryType> _DeliveryTypes;
        /// <summary>
        /// There are no comments for PaymentProperties in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<PaymentProperty> PaymentProperties
        {
            get
            {
                if ((this._PaymentProperties == null))
                {
                    this._PaymentProperties = base.CreateQuery<PaymentProperty>("[PaymentProperties]");
                }
                return this._PaymentProperties;
            }
        }
        private global::System.Data.Objects.ObjectQuery<PaymentProperty> _PaymentProperties;
        /// <summary>
        /// There are no comments for PaymentPropertyValues in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<PaymentPropertyValue> PaymentPropertyValues
        {
            get
            {
                if ((this._PaymentPropertyValues == null))
                {
                    this._PaymentPropertyValues = base.CreateQuery<PaymentPropertyValue>("[PaymentPropertyValues]");
                }
                return this._PaymentPropertyValues;
            }
        }
        private global::System.Data.Objects.ObjectQuery<PaymentPropertyValue> _PaymentPropertyValues;
        /// <summary>
        /// There are no comments for PaymentTypes in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<PaymentType> PaymentTypes
        {
            get
            {
                if ((this._PaymentTypes == null))
                {
                    this._PaymentTypes = base.CreateQuery<PaymentType>("[PaymentTypes]");
                }
                return this._PaymentTypes;
            }
        }
        private global::System.Data.Objects.ObjectQuery<PaymentType> _PaymentTypes;
        /// <summary>
        /// There are no comments for Orders in the schema.
        /// </summary>
        public void AddToOrders(Order order)
        {
            base.AddObject("Orders", order);
        }
        /// <summary>
        /// There are no comments for OrderItems in the schema.
        /// </summary>
        public void AddToOrderItems(OrderItem orderItem)
        {
            base.AddObject("OrderItems", orderItem);
        }
        /// <summary>
        /// There are no comments for DeliveryTypes in the schema.
        /// </summary>
        public void AddToDeliveryTypes(DeliveryType deliveryType)
        {
            base.AddObject("DeliveryTypes", deliveryType);
        }
        /// <summary>
        /// There are no comments for PaymentProperties in the schema.
        /// </summary>
        public void AddToPaymentProperties(PaymentProperty paymentProperty)
        {
            base.AddObject("PaymentProperties", paymentProperty);
        }
        /// <summary>
        /// There are no comments for PaymentPropertyValues in the schema.
        /// </summary>
        public void AddToPaymentPropertyValues(PaymentPropertyValue paymentPropertyValue)
        {
            base.AddObject("PaymentPropertyValues", paymentPropertyValue);
        }
        /// <summary>
        /// There are no comments for PaymentTypes in the schema.
        /// </summary>
        public void AddToPaymentTypes(PaymentType paymentType)
        {
            base.AddObject("PaymentTypes", paymentType);
        }
    }
    /// <summary>
    /// There are no comments for shop_Orders.Order in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="shop_Orders", Name="Order")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Order : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Order object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        public static Order CreateOrder(int id)
        {
            Order order = new Order();
            order.Id = id;
            return order;
        }
        /// <summary>
        /// There are no comments for Property AdditionalDeliveryInfo in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string AdditionalDeliveryInfo
        {
            get
            {
                return this._AdditionalDeliveryInfo;
            }
            set
            {
                this.OnAdditionalDeliveryInfoChanging(value);
                this.ReportPropertyChanging("AdditionalDeliveryInfo");
                this._AdditionalDeliveryInfo = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("AdditionalDeliveryInfo");
                this.OnAdditionalDeliveryInfoChanged();
            }
        }
        private string _AdditionalDeliveryInfo;
        partial void OnAdditionalDeliveryInfoChanging(string value);
        partial void OnAdditionalDeliveryInfoChanged();
        /// <summary>
        /// There are no comments for Property AdditionalProperties in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string AdditionalProperties
        {
            get
            {
                return this._AdditionalProperties;
            }
            set
            {
                this.OnAdditionalPropertiesChanging(value);
                this.ReportPropertyChanging("AdditionalProperties");
                this._AdditionalProperties = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("AdditionalProperties");
                this.OnAdditionalPropertiesChanged();
            }
        }
        private string _AdditionalProperties;
        partial void OnAdditionalPropertiesChanging(string value);
        partial void OnAdditionalPropertiesChanged();
        /// <summary>
        /// There are no comments for Property BillingEmail in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string BillingEmail
        {
            get
            {
                return this._BillingEmail;
            }
            set
            {
                this.OnBillingEmailChanging(value);
                this.ReportPropertyChanging("BillingEmail");
                this._BillingEmail = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("BillingEmail");
                this.OnBillingEmailChanged();
            }
        }
        private string _BillingEmail;
        partial void OnBillingEmailChanging(string value);
        partial void OnBillingEmailChanged();
        /// <summary>
        /// There are no comments for Property BillingName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string BillingName
        {
            get
            {
                return this._BillingName;
            }
            set
            {
                this.OnBillingNameChanging(value);
                this.ReportPropertyChanging("BillingName");
                this._BillingName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("BillingName");
                this.OnBillingNameChanged();
            }
        }
        private string _BillingName;
        partial void OnBillingNameChanging(string value);
        partial void OnBillingNameChanged();
        /// <summary>
        /// There are no comments for Property BillingPhone in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string BillingPhone
        {
            get
            {
                return this._BillingPhone;
            }
            set
            {
                this.OnBillingPhoneChanging(value);
                this.ReportPropertyChanging("BillingPhone");
                this._BillingPhone = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("BillingPhone");
                this.OnBillingPhoneChanged();
            }
        }
        private string _BillingPhone;
        partial void OnBillingPhoneChanging(string value);
        partial void OnBillingPhoneChanged();
        /// <summary>
        /// There are no comments for Property DeliveryAddress in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string DeliveryAddress
        {
            get
            {
                return this._DeliveryAddress;
            }
            set
            {
                this.OnDeliveryAddressChanging(value);
                this.ReportPropertyChanging("DeliveryAddress");
                this._DeliveryAddress = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("DeliveryAddress");
                this.OnDeliveryAddressChanged();
            }
        }
        private string _DeliveryAddress;
        partial void OnDeliveryAddressChanging(string value);
        partial void OnDeliveryAddressChanged();
        /// <summary>
        /// There are no comments for Property DeliveryName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string DeliveryName
        {
            get
            {
                return this._DeliveryName;
            }
            set
            {
                this.OnDeliveryNameChanging(value);
                this.ReportPropertyChanging("DeliveryName");
                this._DeliveryName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("DeliveryName");
                this.OnDeliveryNameChanged();
            }
        }
        private string _DeliveryName;
        partial void OnDeliveryNameChanging(string value);
        partial void OnDeliveryNameChanged();
        /// <summary>
        /// There are no comments for Property DeliveryPhone in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string DeliveryPhone
        {
            get
            {
                return this._DeliveryPhone;
            }
            set
            {
                this.OnDeliveryPhoneChanging(value);
                this.ReportPropertyChanging("DeliveryPhone");
                this._DeliveryPhone = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("DeliveryPhone");
                this.OnDeliveryPhoneChanged();
            }
        }
        private string _DeliveryPhone;
        partial void OnDeliveryPhoneChanging(string value);
        partial void OnDeliveryPhoneChanged();
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property OrderDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> OrderDate
        {
            get
            {
                return this._OrderDate;
            }
            set
            {
                this.OnOrderDateChanging(value);
                this.ReportPropertyChanging("OrderDate");
                this._OrderDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("OrderDate");
                this.OnOrderDateChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _OrderDate;
        partial void OnOrderDateChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnOrderDateChanged();
        /// <summary>
        /// There are no comments for OrderItems in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("shop_Orders", "OrderOrderItem", "OrderItem")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<OrderItem> OrderItems
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<OrderItem>("shop_Orders.OrderOrderItem", "OrderItem");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<OrderItem>("shop_Orders.OrderOrderItem", "OrderItem", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for DeliveryType in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("shop_Orders", "DeliveryTypeOrder", "DeliveryType")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public DeliveryType DeliveryType
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<DeliveryType>("shop_Orders.DeliveryTypeOrder", "DeliveryType").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<DeliveryType>("shop_Orders.DeliveryTypeOrder", "DeliveryType").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for DeliveryType in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<DeliveryType> DeliveryTypeReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<DeliveryType>("shop_Orders.DeliveryTypeOrder", "DeliveryType");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<DeliveryType>("shop_Orders.DeliveryTypeOrder", "DeliveryType", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for PaymentType in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("shop_Orders", "PaymentTypeOrder", "PaymentType")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public PaymentType PaymentType
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<PaymentType>("shop_Orders.PaymentTypeOrder", "PaymentType").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<PaymentType>("shop_Orders.PaymentTypeOrder", "PaymentType").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for PaymentType in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<PaymentType> PaymentTypeReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<PaymentType>("shop_Orders.PaymentTypeOrder", "PaymentType");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<PaymentType>("shop_Orders.PaymentTypeOrder", "PaymentType", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for PaymentPropertyValues in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("shop_Orders", "OrderPaymentPropertyValue", "PaymentPropertyValue")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<PaymentPropertyValue> PaymentPropertyValues
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<PaymentPropertyValue>("shop_Orders.OrderPaymentPropertyValue", "PaymentPropertyValue");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<PaymentPropertyValue>("shop_Orders.OrderPaymentPropertyValue", "PaymentPropertyValue", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for shop_Orders.OrderItem in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="shop_Orders", Name="OrderItem")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class OrderItem : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new OrderItem object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        /// <param name="price">Initial value of Price.</param>
        /// <param name="productId">Initial value of ProductId.</param>
        /// <param name="quantity">Initial value of Quantity.</param>
        public static OrderItem CreateOrderItem(int id, float price, int productId, int quantity)
        {
            OrderItem orderItem = new OrderItem();
            orderItem.Id = id;
            orderItem.Price = price;
            orderItem.ProductId = productId;
            orderItem.Quantity = quantity;
            return orderItem;
        }
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this.ReportPropertyChanging("Description");
                this._Description = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Description");
                this.OnDescriptionChanged();
            }
        }
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Image in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Image
        {
            get
            {
                return this._Image;
            }
            set
            {
                this.OnImageChanging(value);
                this.ReportPropertyChanging("Image");
                this._Image = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Image");
                this.OnImageChanged();
            }
        }
        private string _Image;
        partial void OnImageChanging(string value);
        partial void OnImageChanged();
        /// <summary>
        /// There are no comments for Property Price in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public float Price
        {
            get
            {
                return this._Price;
            }
            set
            {
                this.OnPriceChanging(value);
                this.ReportPropertyChanging("Price");
                this._Price = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Price");
                this.OnPriceChanged();
            }
        }
        private float _Price;
        partial void OnPriceChanging(float value);
        partial void OnPriceChanged();
        /// <summary>
        /// There are no comments for Property ProductAttributes in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductAttributes
        {
            get
            {
                return this._ProductAttributes;
            }
            set
            {
                this.OnProductAttributesChanging(value);
                this.ReportPropertyChanging("ProductAttributes");
                this._ProductAttributes = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("ProductAttributes");
                this.OnProductAttributesChanged();
            }
        }
        private string _ProductAttributes;
        partial void OnProductAttributesChanging(string value);
        partial void OnProductAttributesChanged();
        /// <summary>
        /// There are no comments for Property ProductId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductId
        {
            get
            {
                return this._ProductId;
            }
            set
            {
                this.OnProductIdChanging(value);
                this.ReportPropertyChanging("ProductId");
                this._ProductId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ProductId");
                this.OnProductIdChanged();
            }
        }
        private int _ProductId;
        partial void OnProductIdChanging(int value);
        partial void OnProductIdChanged();
        /// <summary>
        /// There are no comments for Property Quantity in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity
        {
            get
            {
                return this._Quantity;
            }
            set
            {
                this.OnQuantityChanging(value);
                this.ReportPropertyChanging("Quantity");
                this._Quantity = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Quantity");
                this.OnQuantityChanged();
            }
        }
        private int _Quantity;
        partial void OnQuantityChanging(int value);
        partial void OnQuantityChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Order in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("shop_Orders", "OrderOrderItem", "Order")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Order Order
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Order>("shop_Orders.OrderOrderItem", "Order").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Order>("shop_Orders.OrderOrderItem", "Order").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Order in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Order> OrderReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Order>("shop_Orders.OrderOrderItem", "Order");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Order>("shop_Orders.OrderOrderItem", "Order", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for shop_Orders.DeliveryType in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="shop_Orders", Name="DeliveryType")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class DeliveryType : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new DeliveryType object.
        /// </summary>
        /// <param name="disabled">Initial value of Disabled.</param>
        /// <param name="id">Initial value of Id.</param>
        /// <param name="name">Initial value of Name.</param>
        public static DeliveryType CreateDeliveryType(bool disabled, int id, string name)
        {
            DeliveryType deliveryType = new DeliveryType();
            deliveryType.Disabled = disabled;
            deliveryType.Id = id;
            deliveryType.Name = name;
            return deliveryType;
        }
        /// <summary>
        /// There are no comments for Property Disabled in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public bool Disabled
        {
            get
            {
                return this._Disabled;
            }
            set
            {
                this.OnDisabledChanging(value);
                this.ReportPropertyChanging("Disabled");
                this._Disabled = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Disabled");
                this.OnDisabledChanged();
            }
        }
        private bool _Disabled;
        partial void OnDisabledChanging(bool value);
        partial void OnDisabledChanged();
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property AdditionalFee in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<float> AdditionalFee
        {
            get
            {
                return this._AdditionalFee;
            }
            set
            {
                this.OnAdditionalFeeChanging(value);
                this.ReportPropertyChanging("AdditionalFee");
                this._AdditionalFee = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("AdditionalFee");
                this.OnAdditionalFeeChanged();
            }
        }
        private global::System.Nullable<float> _AdditionalFee;
        partial void OnAdditionalFeeChanging(global::System.Nullable<float> value);
        partial void OnAdditionalFeeChanged();
        /// <summary>
        /// There are no comments for Orders in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("shop_Orders", "DeliveryTypeOrder", "Order")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Order> Orders
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Order>("shop_Orders.DeliveryTypeOrder", "Order");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Order>("shop_Orders.DeliveryTypeOrder", "Order", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for PaymentTypes in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("shop_Orders", "DeliveryTypePaymentType", "PaymentType")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<PaymentType> PaymentTypes
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<PaymentType>("shop_Orders.DeliveryTypePaymentType", "PaymentType");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<PaymentType>("shop_Orders.DeliveryTypePaymentType", "PaymentType", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for shop_Orders.PaymentProperty in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="shop_Orders", Name="PaymentProperty")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class PaymentProperty : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new PaymentProperty object.
        /// </summary>
        /// <param name="disabled">Initial value of Disabled.</param>
        /// <param name="id">Initial value of Id.</param>
        /// <param name="name">Initial value of Name.</param>
        public static PaymentProperty CreatePaymentProperty(bool disabled, int id, string name)
        {
            PaymentProperty paymentProperty = new PaymentProperty();
            paymentProperty.Disabled = disabled;
            paymentProperty.Id = id;
            paymentProperty.Name = name;
            return paymentProperty;
        }
        /// <summary>
        /// There are no comments for Property Disabled in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public bool Disabled
        {
            get
            {
                return this._Disabled;
            }
            set
            {
                this.OnDisabledChanging(value);
                this.ReportPropertyChanging("Disabled");
                this._Disabled = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Disabled");
                this.OnDisabledChanged();
            }
        }
        private bool _Disabled;
        partial void OnDisabledChanging(bool value);
        partial void OnDisabledChanged();
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property FieldName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string FieldName
        {
            get
            {
                return this._FieldName;
            }
            set
            {
                this.OnFieldNameChanging(value);
                this.ReportPropertyChanging("FieldName");
                this._FieldName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("FieldName");
                this.OnFieldNameChanged();
            }
        }
        private string _FieldName;
        partial void OnFieldNameChanging(string value);
        partial void OnFieldNameChanged();
        /// <summary>
        /// There are no comments for PaymentType in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("shop_Orders", "PaymentTypePaymentProperty", "PaymentType")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public PaymentType PaymentType
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<PaymentType>("shop_Orders.PaymentTypePaymentProperty", "PaymentType").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<PaymentType>("shop_Orders.PaymentTypePaymentProperty", "PaymentType").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for PaymentType in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<PaymentType> PaymentTypeReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<PaymentType>("shop_Orders.PaymentTypePaymentProperty", "PaymentType");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<PaymentType>("shop_Orders.PaymentTypePaymentProperty", "PaymentType", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for PaymentPropertyValue in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("shop_Orders", "PaymentPropertyPaymentPropertyValue", "PaymentPropertyValue")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<PaymentPropertyValue> PaymentPropertyValue
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<PaymentPropertyValue>("shop_Orders.PaymentPropertyPaymentPropertyValue", "PaymentPropertyValue");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<PaymentPropertyValue>("shop_Orders.PaymentPropertyPaymentPropertyValue", "PaymentPropertyValue", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for shop_Orders.PaymentPropertyValue in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="shop_Orders", Name="PaymentPropertyValue")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class PaymentPropertyValue : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new PaymentPropertyValue object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        public static PaymentPropertyValue CreatePaymentPropertyValue(int id)
        {
            PaymentPropertyValue paymentPropertyValue = new PaymentPropertyValue();
            paymentPropertyValue.Id = id;
            return paymentPropertyValue;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Value in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Value
        {
            get
            {
                return this._Value;
            }
            set
            {
                this.OnValueChanging(value);
                this.ReportPropertyChanging("Value");
                this._Value = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Value");
                this.OnValueChanged();
            }
        }
        private string _Value;
        partial void OnValueChanging(string value);
        partial void OnValueChanged();
        /// <summary>
        /// There are no comments for PaymentProperty in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("shop_Orders", "PaymentPropertyPaymentPropertyValue", "PaymentProperty")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public PaymentProperty PaymentProperty
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<PaymentProperty>("shop_Orders.PaymentPropertyPaymentPropertyValue", "PaymentProperty").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<PaymentProperty>("shop_Orders.PaymentPropertyPaymentPropertyValue", "PaymentProperty").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for PaymentProperty in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<PaymentProperty> PaymentPropertyReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<PaymentProperty>("shop_Orders.PaymentPropertyPaymentPropertyValue", "PaymentProperty");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<PaymentProperty>("shop_Orders.PaymentPropertyPaymentPropertyValue", "PaymentProperty", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Order in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("shop_Orders", "OrderPaymentPropertyValue", "Order")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Order Order
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Order>("shop_Orders.OrderPaymentPropertyValue", "Order").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Order>("shop_Orders.OrderPaymentPropertyValue", "Order").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Order in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Order> OrderReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Order>("shop_Orders.OrderPaymentPropertyValue", "Order");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Order>("shop_Orders.OrderPaymentPropertyValue", "Order", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for shop_Orders.PaymentType in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="shop_Orders", Name="PaymentType")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class PaymentType : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new PaymentType object.
        /// </summary>
        /// <param name="disabled">Initial value of Disabled.</param>
        /// <param name="id">Initial value of Id.</param>
        /// <param name="name">Initial value of Name.</param>
        public static PaymentType CreatePaymentType(bool disabled, int id, string name)
        {
            PaymentType paymentType = new PaymentType();
            paymentType.Disabled = disabled;
            paymentType.Id = id;
            paymentType.Name = name;
            return paymentType;
        }
        /// <summary>
        /// There are no comments for Property Disabled in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public bool Disabled
        {
            get
            {
                return this._Disabled;
            }
            set
            {
                this.OnDisabledChanging(value);
                this.ReportPropertyChanging("Disabled");
                this._Disabled = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Disabled");
                this.OnDisabledChanged();
            }
        }
        private bool _Disabled;
        partial void OnDisabledChanging(bool value);
        partial void OnDisabledChanged();
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property DocumentName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentName
        {
            get
            {
                return this._DocumentName;
            }
            set
            {
                this.OnDocumentNameChanging(value);
                this.ReportPropertyChanging("DocumentName");
                this._DocumentName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("DocumentName");
                this.OnDocumentNameChanged();
            }
        }
        private string _DocumentName;
        partial void OnDocumentNameChanging(string value);
        partial void OnDocumentNameChanged();
        /// <summary>
        /// There are no comments for DeliveryTypes in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("shop_Orders", "DeliveryTypePaymentType", "DeliveryType")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<DeliveryType> DeliveryTypes
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<DeliveryType>("shop_Orders.DeliveryTypePaymentType", "DeliveryType");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<DeliveryType>("shop_Orders.DeliveryTypePaymentType", "DeliveryType", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Orders in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("shop_Orders", "PaymentTypeOrder", "Order")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Order> Orders
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Order>("shop_Orders.PaymentTypeOrder", "Order");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Order>("shop_Orders.PaymentTypeOrder", "Order", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for PaymentProperties in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("shop_Orders", "PaymentTypePaymentProperty", "PaymentProperty")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<PaymentProperty> PaymentProperties
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<PaymentProperty>("shop_Orders.PaymentTypePaymentProperty", "PaymentProperty");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<PaymentProperty>("shop_Orders.PaymentTypePaymentProperty", "PaymentProperty", value);
                }
            }
        }
    }
}
