//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("gbua_tripsModel", "BrandsCarAds", "Brands", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Trips.Web.Models.Brands), "CarAds", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Trips.Web.Models.CarAds))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("gbua_tripsModel", "CarAdsCarAdImages", "CarAds", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Trips.Web.Models.CarAds), "CarAdImages", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Trips.Web.Models.CarAdImages))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("gbua_tripsModel", "CarAdsCarAdDescriptions", "CarAds", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Trips.Web.Models.CarAds), "CarAdDescriptions", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Trips.Web.Models.CarAdDescriptions))]

// Original file name:
// Generation date: 19/02/2010 14:44:30
namespace Trips.Web.Models
{
    
    /// <summary>
    /// There are no comments for CarAdStorage in the schema.
    /// </summary>
    public partial class CarAdStorage : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new CarAdStorage object using the connection string found in the 'CarAdStorage' section of the application configuration file.
        /// </summary>
        public CarAdStorage() : 
                base("name=CarAdStorage", "CarAdStorage")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new CarAdStorage object.
        /// </summary>
        public CarAdStorage(string connectionString) : 
                base(connectionString, "CarAdStorage")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new CarAdStorage object.
        /// </summary>
        public CarAdStorage(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "CarAdStorage")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for Brands in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Brands> Brands
        {
            get
            {
                if ((this._Brands == null))
                {
                    this._Brands = base.CreateQuery<Brands>("[Brands]");
                }
                return this._Brands;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Brands> _Brands;
        /// <summary>
        /// There are no comments for CarAdDescriptions in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<CarAdDescriptions> CarAdDescriptions
        {
            get
            {
                if ((this._CarAdDescriptions == null))
                {
                    this._CarAdDescriptions = base.CreateQuery<CarAdDescriptions>("[CarAdDescriptions]");
                }
                return this._CarAdDescriptions;
            }
        }
        private global::System.Data.Objects.ObjectQuery<CarAdDescriptions> _CarAdDescriptions;
        /// <summary>
        /// There are no comments for CarAdImages in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<CarAdImages> CarAdImages
        {
            get
            {
                if ((this._CarAdImages == null))
                {
                    this._CarAdImages = base.CreateQuery<CarAdImages>("[CarAdImages]");
                }
                return this._CarAdImages;
            }
        }
        private global::System.Data.Objects.ObjectQuery<CarAdImages> _CarAdImages;
        /// <summary>
        /// There are no comments for CarAds in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<CarAds> CarAds
        {
            get
            {
                if ((this._CarAds == null))
                {
                    this._CarAds = base.CreateQuery<CarAds>("[CarAds]");
                }
                return this._CarAds;
            }
        }
        private global::System.Data.Objects.ObjectQuery<CarAds> _CarAds;
        /// <summary>
        /// There are no comments for Brands in the schema.
        /// </summary>
        public void AddToBrands(Brands brands)
        {
            base.AddObject("Brands", brands);
        }
        /// <summary>
        /// There are no comments for CarAdDescriptions in the schema.
        /// </summary>
        public void AddToCarAdDescriptions(CarAdDescriptions carAdDescriptions)
        {
            base.AddObject("CarAdDescriptions", carAdDescriptions);
        }
        /// <summary>
        /// There are no comments for CarAdImages in the schema.
        /// </summary>
        public void AddToCarAdImages(CarAdImages carAdImages)
        {
            base.AddObject("CarAdImages", carAdImages);
        }
        /// <summary>
        /// There are no comments for CarAds in the schema.
        /// </summary>
        public void AddToCarAds(CarAds carAds)
        {
            base.AddObject("CarAds", carAds);
        }
    }
    /// <summary>
    /// There are no comments for gbua_tripsModel.Brands in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="gbua_tripsModel", Name="Brands")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Brands : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Brands object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        /// <param name="name">Initial value of Name.</param>
        public static Brands CreateBrands(long id, string name)
        {
            Brands brands = new Brands();
            brands.Id = id;
            brands.Name = name;
            return brands;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private long _Id;
        partial void OnIdChanging(long value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for CarAds in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("gbua_tripsModel", "BrandsCarAds", "CarAds")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<CarAds> CarAds
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<CarAds>("gbua_tripsModel.BrandsCarAds", "CarAds");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<CarAds>("gbua_tripsModel.BrandsCarAds", "CarAds", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for gbua_tripsModel.CarAdDescriptions in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="gbua_tripsModel", Name="CarAdDescriptions")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class CarAdDescriptions : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new CarAdDescriptions object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        /// <param name="language">Initial value of Language.</param>
        public static CarAdDescriptions CreateCarAdDescriptions(long id, string language)
        {
            CarAdDescriptions carAdDescriptions = new CarAdDescriptions();
            carAdDescriptions.Id = id;
            carAdDescriptions.Language = language;
            return carAdDescriptions;
        }
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this.ReportPropertyChanging("Description");
                this._Description = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Description");
                this.OnDescriptionChanged();
            }
        }
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private long _Id;
        partial void OnIdChanging(long value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Keywords in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Keywords
        {
            get
            {
                return this._Keywords;
            }
            set
            {
                this.OnKeywordsChanging(value);
                this.ReportPropertyChanging("Keywords");
                this._Keywords = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Keywords");
                this.OnKeywordsChanged();
            }
        }
        private string _Keywords;
        partial void OnKeywordsChanging(string value);
        partial void OnKeywordsChanged();
        /// <summary>
        /// There are no comments for Property Language in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Language
        {
            get
            {
                return this._Language;
            }
            set
            {
                this.OnLanguageChanging(value);
                this.ReportPropertyChanging("Language");
                this._Language = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Language");
                this.OnLanguageChanged();
            }
        }
        private string _Language;
        partial void OnLanguageChanging(string value);
        partial void OnLanguageChanged();
        /// <summary>
        /// There are no comments for Property ShortDescription in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ShortDescription
        {
            get
            {
                return this._ShortDescription;
            }
            set
            {
                this.OnShortDescriptionChanging(value);
                this.ReportPropertyChanging("ShortDescription");
                this._ShortDescription = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("ShortDescription");
                this.OnShortDescriptionChanged();
            }
        }
        private string _ShortDescription;
        partial void OnShortDescriptionChanging(string value);
        partial void OnShortDescriptionChanged();
        /// <summary>
        /// There are no comments for Property Text in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Text
        {
            get
            {
                return this._Text;
            }
            set
            {
                this.OnTextChanging(value);
                this.ReportPropertyChanging("Text");
                this._Text = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Text");
                this.OnTextChanged();
            }
        }
        private string _Text;
        partial void OnTextChanging(string value);
        partial void OnTextChanged();
        /// <summary>
        /// There are no comments for CarAds in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("gbua_tripsModel", "CarAdsCarAdDescriptions", "CarAds")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public CarAds CarAds
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<CarAds>("gbua_tripsModel.CarAdsCarAdDescriptions", "CarAds").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<CarAds>("gbua_tripsModel.CarAdsCarAdDescriptions", "CarAds").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for CarAds in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<CarAds> CarAdsReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<CarAds>("gbua_tripsModel.CarAdsCarAdDescriptions", "CarAds");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<CarAds>("gbua_tripsModel.CarAdsCarAdDescriptions", "CarAds", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for gbua_tripsModel.CarAdImages in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="gbua_tripsModel", Name="CarAdImages")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class CarAdImages : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new CarAdImages object.
        /// </summary>
        /// <param name="default">Initial value of Default.</param>
        /// <param name="id">Initial value of Id.</param>
        /// <param name="imageSource">Initial value of ImageSource.</param>
        public static CarAdImages CreateCarAdImages(bool @default, long id, string imageSource)
        {
            CarAdImages carAdImages = new CarAdImages();
            carAdImages.Default = @default;
            carAdImages.Id = id;
            carAdImages.ImageSource = imageSource;
            return carAdImages;
        }
        /// <summary>
        /// There are no comments for Property Default in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public bool Default
        {
            get
            {
                return this._Default;
            }
            set
            {
                this.OnDefaultChanging(value);
                this.ReportPropertyChanging("Default");
                this._Default = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Default");
                this.OnDefaultChanged();
            }
        }
        private bool _Default;
        partial void OnDefaultChanging(bool value);
        partial void OnDefaultChanged();
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private long _Id;
        partial void OnIdChanging(long value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property ImageSource in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageSource
        {
            get
            {
                return this._ImageSource;
            }
            set
            {
                this.OnImageSourceChanging(value);
                this.ReportPropertyChanging("ImageSource");
                this._ImageSource = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("ImageSource");
                this.OnImageSourceChanged();
            }
        }
        private string _ImageSource;
        partial void OnImageSourceChanging(string value);
        partial void OnImageSourceChanged();
        /// <summary>
        /// There are no comments for CarAd in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("gbua_tripsModel", "CarAdsCarAdImages", "CarAds")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public CarAds CarAd
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<CarAds>("gbua_tripsModel.CarAdsCarAdImages", "CarAds").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<CarAds>("gbua_tripsModel.CarAdsCarAdImages", "CarAds").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for CarAd in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<CarAds> CarAdReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<CarAds>("gbua_tripsModel.CarAdsCarAdImages", "CarAds");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<CarAds>("gbua_tripsModel.CarAdsCarAdImages", "CarAds", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for gbua_tripsModel.CarAds in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="gbua_tripsModel", Name="CarAds")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class CarAds : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new CarAds object.
        /// </summary>
        /// <param name="class">Initial value of Class.</param>
        /// <param name="id">Initial value of Id.</param>
        /// <param name="model">Initial value of Model.</param>
        /// <param name="year">Initial value of Year.</param>
        public static CarAds CreateCarAds(long @class, long id, string model, long year)
        {
            CarAds carAds = new CarAds();
            carAds.Class = @class;
            carAds.Id = id;
            carAds.Model = model;
            carAds.Year = year;
            return carAds;
        }
        /// <summary>
        /// There are no comments for Property Class in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long Class
        {
            get
            {
                return this._Class;
            }
            set
            {
                this.OnClassChanging(value);
                this.ReportPropertyChanging("Class");
                this._Class = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Class");
                this.OnClassChanged();
            }
        }
        private long _Class;
        partial void OnClassChanging(long value);
        partial void OnClassChanged();
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private long _Id;
        partial void OnIdChanging(long value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Model in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Model
        {
            get
            {
                return this._Model;
            }
            set
            {
                this.OnModelChanging(value);
                this.ReportPropertyChanging("Model");
                this._Model = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Model");
                this.OnModelChanged();
            }
        }
        private string _Model;
        partial void OnModelChanging(string value);
        partial void OnModelChanged();
        /// <summary>
        /// There are no comments for Property Year in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long Year
        {
            get
            {
                return this._Year;
            }
            set
            {
                this.OnYearChanging(value);
                this.ReportPropertyChanging("Year");
                this._Year = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Year");
                this.OnYearChanged();
            }
        }
        private long _Year;
        partial void OnYearChanging(long value);
        partial void OnYearChanged();
        /// <summary>
        /// There are no comments for Brands in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("gbua_tripsModel", "BrandsCarAds", "Brands")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Brands Brands
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Brands>("gbua_tripsModel.BrandsCarAds", "Brands").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Brands>("gbua_tripsModel.BrandsCarAds", "Brands").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Brands in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Brands> BrandsReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Brands>("gbua_tripsModel.BrandsCarAds", "Brands");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Brands>("gbua_tripsModel.BrandsCarAds", "Brands", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for CarAdDescriptions in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("gbua_tripsModel", "CarAdsCarAdDescriptions", "CarAdDescriptions")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<CarAdDescriptions> CarAdDescriptions
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<CarAdDescriptions>("gbua_tripsModel.CarAdsCarAdDescriptions", "CarAdDescriptions");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<CarAdDescriptions>("gbua_tripsModel.CarAdsCarAdDescriptions", "CarAdDescriptions", value);
                }
            }
        }
    }
}
