//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("Model", "FK_Objects_Clients", "Clients", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(PolialClean.Models.Clients), "Objects", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(PolialClean.Models.Objects))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("Model", "FK_Recomendations_Clients", "Clients", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(PolialClean.Models.Clients), "Recomendations", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(PolialClean.Models.Recomendations))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("Model", "FK_SiteContent_SiteContent", "SiteContent", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(PolialClean.Models.SiteContent), "SiteContent1", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(PolialClean.Models.SiteContent))]

// Original file name:
// Generation date: 15/12/2009 15:28:56
namespace PolialClean.Models
{
    
    /// <summary>
    /// There are no comments for DataStorage in the schema.
    /// </summary>
    public partial class DataStorage : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new DataStorage object using the connection string found in the 'DataStorage' section of the application configuration file.
        /// </summary>
        public DataStorage() : 
                base("name=DataStorage", "DataStorage")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new DataStorage object.
        /// </summary>
        public DataStorage(string connectionString) : 
                base(connectionString, "DataStorage")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new DataStorage object.
        /// </summary>
        public DataStorage(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "DataStorage")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for Clients in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Clients> Clients
        {
            get
            {
                if ((this._Clients == null))
                {
                    this._Clients = base.CreateQuery<Clients>("[Clients]");
                }
                return this._Clients;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Clients> _Clients;
        /// <summary>
        /// There are no comments for Recomendations in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Recomendations> Recomendations
        {
            get
            {
                if ((this._Recomendations == null))
                {
                    this._Recomendations = base.CreateQuery<Recomendations>("[Recomendations]");
                }
                return this._Recomendations;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Recomendations> _Recomendations;
        /// <summary>
        /// There are no comments for SiteContent in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<SiteContent> SiteContent
        {
            get
            {
                if ((this._SiteContent == null))
                {
                    this._SiteContent = base.CreateQuery<SiteContent>("[SiteContent]");
                }
                return this._SiteContent;
            }
        }
        private global::System.Data.Objects.ObjectQuery<SiteContent> _SiteContent;
        /// <summary>
        /// There are no comments for Objects in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Objects> Objects
        {
            get
            {
                if ((this._Objects == null))
                {
                    this._Objects = base.CreateQuery<Objects>("[Objects]");
                }
                return this._Objects;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Objects> _Objects;
        /// <summary>
        /// There are no comments for Clients in the schema.
        /// </summary>
        public void AddToClients(Clients clients)
        {
            base.AddObject("Clients", clients);
        }
        /// <summary>
        /// There are no comments for Recomendations in the schema.
        /// </summary>
        public void AddToRecomendations(Recomendations recomendations)
        {
            base.AddObject("Recomendations", recomendations);
        }
        /// <summary>
        /// There are no comments for SiteContent in the schema.
        /// </summary>
        public void AddToSiteContent(SiteContent siteContent)
        {
            base.AddObject("SiteContent", siteContent);
        }
        /// <summary>
        /// There are no comments for Objects in the schema.
        /// </summary>
        public void AddToObjects(Objects objects)
        {
            base.AddObject("Objects", objects);
        }
    }
    /// <summary>
    /// There are no comments for Model.Clients in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Model", Name="Clients")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Clients : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Clients object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        public static Clients CreateClients(int id)
        {
            Clients clients = new Clients();
            clients.Id = id;
            return clients;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this.ReportPropertyChanging("Description");
                this._Description = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Description");
                this.OnDescriptionChanged();
            }
        }
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property Logo in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Logo
        {
            get
            {
                return this._Logo;
            }
            set
            {
                this.OnLogoChanging(value);
                this.ReportPropertyChanging("Logo");
                this._Logo = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Logo");
                this.OnLogoChanged();
            }
        }
        private string _Logo;
        partial void OnLogoChanging(string value);
        partial void OnLogoChanged();
        /// <summary>
        /// There are no comments for Objects in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Model", "FK_Objects_Clients", "Objects")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Objects> Objects
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Objects>("Model.FK_Objects_Clients", "Objects");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Objects>("Model.FK_Objects_Clients", "Objects", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Recomendations in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Model", "FK_Recomendations_Clients", "Recomendations")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Recomendations> Recomendations
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Recomendations>("Model.FK_Recomendations_Clients", "Recomendations");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Recomendations>("Model.FK_Recomendations_Clients", "Recomendations", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for Model.Recomendations in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Model", Name="Recomendations")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Recomendations : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Recomendations object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        public static Recomendations CreateRecomendations(int id)
        {
            Recomendations recomendations = new Recomendations();
            recomendations.Id = id;
            return recomendations;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Image in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Image
        {
            get
            {
                return this._Image;
            }
            set
            {
                this.OnImageChanging(value);
                this.ReportPropertyChanging("Image");
                this._Image = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Image");
                this.OnImageChanged();
            }
        }
        private string _Image;
        partial void OnImageChanging(string value);
        partial void OnImageChanged();
        /// <summary>
        /// There are no comments for Property Preview in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Preview
        {
            get
            {
                return this._Preview;
            }
            set
            {
                this.OnPreviewChanging(value);
                this.ReportPropertyChanging("Preview");
                this._Preview = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Preview");
                this.OnPreviewChanged();
            }
        }
        private string _Preview;
        partial void OnPreviewChanging(string value);
        partial void OnPreviewChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this.ReportPropertyChanging("Description");
                this._Description = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Description");
                this.OnDescriptionChanged();
            }
        }
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Clients in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Model", "FK_Recomendations_Clients", "Clients")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Clients Clients
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Clients>("Model.FK_Recomendations_Clients", "Clients").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Clients>("Model.FK_Recomendations_Clients", "Clients").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Clients in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Clients> ClientsReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Clients>("Model.FK_Recomendations_Clients", "Clients");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Clients>("Model.FK_Recomendations_Clients", "Clients", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for Model.SiteContent in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Model", Name="SiteContent")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class SiteContent : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new SiteContent object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        public static SiteContent CreateSiteContent(int id)
        {
            SiteContent siteContent = new SiteContent();
            siteContent.Id = id;
            return siteContent;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Content in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Content
        {
            get
            {
                return this._Content;
            }
            set
            {
                this.OnContentChanging(value);
                this.ReportPropertyChanging("Content");
                this._Content = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Content");
                this.OnContentChanged();
            }
        }
        private string _Content;
        partial void OnContentChanging(string value);
        partial void OnContentChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property SortOrder in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> SortOrder
        {
            get
            {
                return this._SortOrder;
            }
            set
            {
                this.OnSortOrderChanging(value);
                this.ReportPropertyChanging("SortOrder");
                this._SortOrder = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("SortOrder");
                this.OnSortOrderChanged();
            }
        }
        private global::System.Nullable<int> _SortOrder;
        partial void OnSortOrderChanging(global::System.Nullable<int> value);
        partial void OnSortOrderChanged();
        /// <summary>
        /// There are no comments for Children in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Model", "FK_SiteContent_SiteContent", "SiteContent1")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<SiteContent> Children
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<SiteContent>("Model.FK_SiteContent_SiteContent", "SiteContent1");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<SiteContent>("Model.FK_SiteContent_SiteContent", "SiteContent1", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Parent in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Model", "FK_SiteContent_SiteContent", "SiteContent")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public SiteContent Parent
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<SiteContent>("Model.FK_SiteContent_SiteContent", "SiteContent").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<SiteContent>("Model.FK_SiteContent_SiteContent", "SiteContent").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Parent in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<SiteContent> ParentReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<SiteContent>("Model.FK_SiteContent_SiteContent", "SiteContent");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<SiteContent>("Model.FK_SiteContent_SiteContent", "SiteContent", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for Model.Objects in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Model", Name="Objects")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Objects : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Objects object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        public static Objects CreateObjects(int id)
        {
            Objects objects = new Objects();
            objects.Id = id;
            return objects;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Image in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Image
        {
            get
            {
                return this._Image;
            }
            set
            {
                this.OnImageChanging(value);
                this.ReportPropertyChanging("Image");
                this._Image = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Image");
                this.OnImageChanged();
            }
        }
        private string _Image;
        partial void OnImageChanging(string value);
        partial void OnImageChanged();
        /// <summary>
        /// There are no comments for Property Preview in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Preview
        {
            get
            {
                return this._Preview;
            }
            set
            {
                this.OnPreviewChanging(value);
                this.ReportPropertyChanging("Preview");
                this._Preview = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Preview");
                this.OnPreviewChanged();
            }
        }
        private string _Preview;
        partial void OnPreviewChanging(string value);
        partial void OnPreviewChanged();
        /// <summary>
        /// There are no comments for Clients in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Model", "FK_Objects_Clients", "Clients")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Clients Clients
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Clients>("Model.FK_Objects_Clients", "Clients").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Clients>("Model.FK_Objects_Clients", "Clients").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Clients in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Clients> ClientsReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Clients>("Model.FK_Objects_Clients", "Clients");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Clients>("Model.FK_Objects_Clients", "Clients", value);
                }
            }
        }
    }
}
