<?xml version="1.0" encoding="utf-8"?>
<Database Name="1gb_Tina" EntityNamespace="GalleryContext" ContextNamespace="Galleria" Class="GalleryDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=mssql2.1gb.ua;Initial Catalog=1gb_Tina;Persist Security Info=True;User ID=1gb_amc" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="_1gb_TinaConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Gallery" Member="Galleries">
    <Type Name="Gallery">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AlbumID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Picture" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Thumbnail" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="SortOrder" Type="System.Int32" DbType="int" CanBeNull="false" />
      <Association Name="Album_Gallery" Member="Album" ThisKey="AlbumID" OtherKey="ID" Type="Album" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Albums" Member="Albums">
    <Type Name="Album">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="Year" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Image" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="PhotoImage" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="InvertColors" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Album_Gallery" Member="Galleries" ThisKey="ID" OtherKey="AlbumID" Type="Gallery" />
    </Type>
  </Table>
</Database>