<?xml version="1.0" encoding="utf-8"?>
<Database Name="Drozd_pandemic" Class="EntitiesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=mssql011007.hosting.ua;Initial Catalog=Drozd_pandemic;User ID=Drozd_pandemic" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="PandemicConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.EntitySources" Member="EntitySources">
    <Type Name="EntitySource">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Association Name="EntitySource_Entity" Member="Entities" ThisKey="ID" OtherKey="SourceID" Type="Entity" />
    </Type>
  </Table>
  <Table Name="dbo.EntityType" Member="EntityTypes">
    <Type Name="EntityType">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Association Name="EntityType_Entity" Member="Entities" ThisKey="ID" OtherKey="TypeID" Type="Entity" />
    </Type>
  </Table>
  <Table Name="dbo.EntityPictures" Member="EntityPictures">
    <Type Name="EntityPicture">
      <Column Name="ID" AutoSync="Never" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Picture" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Preview" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="EntityID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(250)" CanBeNull="false" />
      <Association Name="Entity_EntityPicture" Member="Entity" ThisKey="EntityID" OtherKey="ID" Type="Entity" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.EntityVideos" Member="EntityVideos">
    <Type Name="EntityVideo">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EntityID" Type="System.Int32" DbType="Int" CanBeNull="false" />
      <Column Name="Source" Type="System.String" DbType="VarChar(2000)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Association Name="Entity_EntityVideo" Member="Entity" ThisKey="EntityID" OtherKey="ID" Type="Entity" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.EntityMusic" Member="EntityMusics">
    <Type Name="EntityMusic">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Source" Type="System.String" DbType="VarChar(2000)" CanBeNull="true" />
      <Column Name="FileName" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="EntityID" Type="System.Int32" DbType="Int" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Artist" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Album" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Comments" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Association Name="Entity_EntityMusic" Member="Entity" ThisKey="EntityID" OtherKey="ID" Type="Entity" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Entities" Member="Entities">
    <Type Name="Entity">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="VarChar(2000)" CanBeNull="true" />
      <Column Name="Content" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="TypeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SourceID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Image" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Association Name="Entity_EntityPicture" Member="EntityPictures" ThisKey="ID" OtherKey="EntityID" Type="EntityPicture" />
      <Association Name="Entity_EntityVideo" Member="EntityVideos" ThisKey="ID" OtherKey="EntityID" Type="EntityVideo" />
      <Association Name="Entity_EntityMusic" Member="EntityMusics" ThisKey="ID" OtherKey="EntityID" Type="EntityMusic" />
      <Association Name="Entity_EntityTagMapping" Member="EntityTagMappings" ThisKey="ID" OtherKey="EntityID" Type="EntityTagMapping" />
      <Association Name="EntitySource_Entity" Member="EntitySource" ThisKey="SourceID" OtherKey="ID" Type="EntitySource" IsForeignKey="true" />
      <Association Name="EntityType_Entity" Member="EntityType" ThisKey="TypeID" OtherKey="ID" Type="EntityType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tags" Member="Tags">
    <Type Name="Tag">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Tag" Member="TagName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Tag_EntityTagMapping" Member="EntityTagMappings" ThisKey="ID" OtherKey="TagID" Type="EntityTagMapping" />
    </Type>
  </Table>
  <Table Name="dbo.EntityTagMappings" Member="EntityTagMappings">
    <Type Name="EntityTagMapping">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EntityID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TagID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Entity_EntityTagMapping" Member="Entity" ThisKey="EntityID" OtherKey="ID" Type="Entity" IsForeignKey="true" />
      <Association Name="Tag_EntityTagMapping" Member="Tag" ThisKey="TagID" OtherKey="ID" Type="Tag" IsForeignKey="true" />
    </Type>
  </Table>
</Database>